### ISSUE TITLE
Returning more (or less) than 1 row per `summarise()` group was deprecated in dplyr 1.1.0.

### ISSUE THREAD

**Issue by aleksander-chuikov** [DenchPokepon/fedstatAPIr#1]
Warning message:
Returning more (or less) than 1 row per `summarise()` group was deprecated in dplyr 1.1.0.
i Please use `reframe()` instead.
i When switching from `summarise()` to `reframe()`, remember that `reframe()` always returns an ungrouped data frame and adjust accordingly.
i The deprecated feature was likely used in the fedstatAPIr package.

**Comment by DenchPokepon** [comment]
Большое спасибо за указание устаревшего кода! Поправлю в ближайшее время

**Comment by DenchPokepon** [comment]
dplyr больше не используется в пакете, ошибка устранена
